name: supermarket
description: A new Flutter project.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.10.0
  carousel_slider: ^2.3.1
  cached_network_image: ^2.4.1
  shared_preferences: ^0.5.12+4
  carousel_pro: ^1.0.0
  http: ^0.12.2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0
  cloud_firestore: ^0.16.0+1
  mvc_pattern: ^6.6.4
  fluttertoast: ^7.1.5
  timelines: ^0.0.2+1
  intl_utils: 1.8.0
  pinput: ^0.2.6
  intl: ^0.16.1
  device_info: ^2.0.3
  geocoding: ^1.0.5
  get: ^4.3.8
  google_maps_flutter: ^1.2.0
  sqflite: ^2.0.0+4
  geolocator: ^6.2.1
  #horizontal_calendar_widget: ^1.0.0

dev_dependencies:
    flutter_test:
      sdk: flutter

flutter:
    uses-material-design: true
    assets:
      - assets/images/

